services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      - APP_PORT=3000
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - uoslife-msa-template

  api-database:
    container_name: api-database
    image: postgres:14
    environment:
      - POSTGRES_DB=nestjs-template
      - POSTGRES_USER=uoslife
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - uoslife-pgdata:/var/lib/postgresql/data
    networks:
      - uoslife-msa-template

networks:
  uoslife-msa-template:
    driver: bridge

volumes:
  uoslife-pgdata:
