apiVersion: apps/v1
kind: Deployment
metadata:
  name: uoslife-template
  namespace: uoslife
  labels:
    app: uoslife-template
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uoslife-template
  template:
    metadata:
      labels:
        app: uoslife-template
    spec:
      containers:
        - name: uoslife-template
          image: harbor.uoslife.com/uoslife/uoslife-template:latest
          ports:
            - containerPort: 3000
          env:
            # 공통 설정
            - name: WISE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: uoslife-common-secret
                  key: WISE_API_KEY
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: uoslife-common-secret
                  key: JWT_SECRET_KEY
            - name: SERVER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: uoslife-common-secret
                  key: SERVER_TOKEN
            - name: POD_CIDR
              valueFrom:
                secretKeyRef:
                  name: uoslife-common-secret
                  key: POD_CIDR

            # 서비스별 설정 (Opaque)
            - name: APP_ENV
              value: production
            - name: APP_URL
              value: https://api.uoslife.team/template
            - name: APP_PORT
              value: 3000

            # 서비스별 설정 (Secret)
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: uoslife-template-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: uoslife-template-secret
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: uoslife-template-secret
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: uoslife-template-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uoslife-template-secret
                  key: DB_PASSWORD

          imagePullPolicy: Always
      imagePullSecrets:
        - name: harbor.uoslife.com
---
apiVersion: v1
kind: Service
metadata:
  name: uoslife-template
  namespace: uoslife
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
      app: uoslife-template
