apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uoslife-template-ingress
  namespace: uoslife
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
  - host: api.uoslife.team
    http:
      paths:
      - path: /template
        pathType: Prefix
        backend:
          service:
            name: uoslife-template
            port:
              number: 3000
